<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bank.Domain\Bank.Domain.csproj" />
    <ProjectReference Include="..\Bank.Infrastructure\Bank.Infrastructure.csproj" />
    <ProjectReference Include="..\Bank.Core\Bank.Core.csproj" />
  </ItemGroup>

</Project>
